# create a docker-compose.yml file
version: "3"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "9000:9000"
  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"